export { desert } from './DesertMapGenerator'
export { ocean } from './OceanMapGenerator'
export { iceland } from './IcelandMapGenerator'
export { grassland } from './GrasslandMapGenerator'
export { tropical } from './TropicalMapGenerator'
export { origin } from './OriginMapGenerator'
export { BaseMapGenerator as base } from './BaseMapGenerator'
